import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FreHelp Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-100 min-h-screen p-8">
        <div className="bg-white rounded-lg shadow p-6 mx-auto max-w-md">
          <h1 className="text-3xl font-semibold mb-4">
            FreHelp Privacy Policy
          </h1>
          <p>Effective Date: November 1st 2023</p>
          <p>
            FreHelp is committed to protecting your privacy. This Privacy Policy
            outlines the information we collect, how we use it, and your choices
            regarding your personal information in connection with our Android
            app for streamlining organizational aid for Fremont shelters.
          </p>
          <h2 className="text-xl font-semibold mt-4">
            1. Information We Collect
          </h2>
          <p>
            1.1 Information You Provide:
            <ul>
              <li>
                Contact information (e.g., name, email address, phone number).
              </li>
              <li>
                Any content, comments, messages, or other information you submit
                within the app.
              </li>
            </ul>
          </p>
          <p>
            1.2 Automatically Collected Information:
            <ul>
              <li>
                Device information, such as your device&apos;s type, model, and
                operating system.
              </li>
              <li>
                Log information, including app usage data, access times, and
                error reports.
              </li>
            </ul>
          </p>
          <h2 className="text-xl font-semibold mt-4">
            2. How We Use Your Information
          </h2>
          <p>
            We may use the information collected for the following purposes:
            <ul>
              <li>To provide and maintain our app&apos;s services.</li>
              <li>To personalize your experience within the app.</li>
              <li>
                To communicate with you, respond to your requests, and provide
                customer support.
              </li>
              <li>
                To analyze and improve our app&apos;s functionality and user
                experience.
              </li>
              <li>To ensure the security and integrity of our app.</li>
            </ul>
          </p>
          <h2 className="text-xl font-semibold mt-4">
            3. Disclosure of Information
          </h2>
          <p>
            We may share your information in the following situations:
            <ul>
              <li>
                With shelter organizations in Fremont, California, as necessary
                to facilitate your interactions.
              </li>
              <li>
                With service providers and contractors who assist us in app
                development and maintenance.
              </li>
              <li>
                In response to a legal request or to protect our rights or the
                rights of others.
              </li>
              <li>
                In connection with any merger, sale of company assets, or other
                business transaction.
              </li>
            </ul>
          </p>
          <h2 className="text-xl font-semibold mt-4">4. Your Choices</h2>
          <p>
            You have the following choices regarding your personal information:
            <ul>
              <li>
                Access, correct, update, or delete your personal information by
                contacting us.
              </li>
              <li>
                Opt out of receiving promotional emails or communications.
              </li>
            </ul>
          </p>
          <h2 className="text-xl font-semibold mt-4">5. Security</h2>
          <p>
            We take reasonable measures to protect your information from
            unauthorized access, disclosure, alteration, or destruction.
            However, no data transmission over the internet or any wireless
            network can be guaranteed to be 100% secure.
          </p>
          <h2 className="text-xl font-semibold mt-4">
            6. Children&apos;s Privacy
          </h2>
          <p>
            Our app is not intended for children under 13 years of age. We do
            not knowingly collect or maintain information from children under 13
            without parental consent.
          </p>
          <h2 className="text-xl font-semibold mt-4">
            7. Changes to this Privacy Policy
          </h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on our website
            or within the app.
          </p>
          <h2 className="text-xl font-semibold mt-4">8. Contact Us</h2>
          <p>
            If you have any questions, concerns, or requests related to this
            Privacy Policy, please contact us at [Insert Contact Information].
          </p>
        </div>
      </div>
    </div>
  );
}
